CREATE DATABASE IF NOT EXISTS compta
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_general_ci;

USE compta;

CREATE TABLE FOURNISSEUR (
    ID  INT(11) NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ARTICLE (
    ID          INT(11) NOT NULL AUTO_INCREMENT,
    REF         VARCHAR(13)  NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    PRIX        DECIMAL(7,2) NOT NULL,
    ID_FOU      INT(11) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_article_fournisseur
        FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BON (
    ID        INT(11) NOT NULL AUTO_INCREMENT,
    NUMERO    INT(11) NOT NULL,
    DATE_CMDE DATETIME NOT NULL,
    DELAI     INT(11) NOT NULL,
    ID_FOU    INT(11) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_bon_fournisseur
        FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMPO (
    ID     INT(11) NOT NULL AUTO_INCREMENT,
    ID_ART INT(11) NOT NULL,
    ID_BON INT(11) NOT NULL,
    QTE    INT(11) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_compo_article FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID),
    CONSTRAINT fk_compo_bon     FOREIGN KEY (ID_BON)  REFERENCES BON(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
