USE compta;

SELECT *
FROM ARTICLE
ORDER BY DESIGNATION ASC;

SELECT *
FROM ARTICLE
ORDER BY PRIX DESC;

SELECT *
FROM ARTICLE
WHERE LOWER(DESIGNATION) LIKE '%boulon%'
ORDER BY PRIX ASC;

SELECT *
FROM ARTICLE
WHERE DESIGNATION LIKE '%sachet%';

SELECT *
FROM ARTICLE
WHERE LOWER(DESIGNATION) LIKE '%sachet%';

SELECT A.ID,
       A.REF,
       A.DESIGNATION,
       A.PRIX,
       F.ID   AS ID_FOURNISSEUR,
       F.NOM  AS NOM_FOURNISSEUR
FROM ARTICLE AS A
JOIN FOURNISSEUR AS F ON A.ID_FOU = F.ID
ORDER BY F.NOM ASC, A.PRIX DESC;

SELECT A.*
FROM ARTICLE AS A
JOIN FOURNISSEUR AS F ON A.ID_FOU = F.ID
WHERE F.NOM = 'Dubois & Fils';

SELECT F.NOM,
       AVG(A.PRIX) AS PRIX_MOYEN
FROM ARTICLE AS A
JOIN FOURNISSEUR AS F ON A.ID_FOU = F.ID
WHERE F.NOM = 'Dubois & Fils';

SELECT F.NOM,
       AVG(A.PRIX) AS PRIX_MOYEN
FROM ARTICLE AS A
JOIN FOURNISSEUR AS F ON A.ID_FOU = F.ID
GROUP BY F.ID, F.NOM;

SELECT *
FROM BON
WHERE DATE_CMDE BETWEEN '2019-03-01 00:00:00'
                    AND '2019-04-05 12:00:00';

SELECT DISTINCT B.*
FROM BON AS B
JOIN COMPO AS C   ON C.ID_BON = B.ID
JOIN ARTICLE AS A ON A.ID = C.ID_ART
WHERE LOWER(A.DESIGNATION) LIKE '%boulon%';

SELECT DISTINCT B.ID,
       B.NUMERO,
       B.DATE_CMDE,
       B.DELAI,
       F.NOM AS NOM_FOURNISSEUR
FROM BON AS B
JOIN FOURNISSEUR AS F ON B.ID_FOU = F.ID
JOIN COMPO AS C       ON C.ID_BON = B.ID
JOIN ARTICLE AS A     ON A.ID = C.ID_ART
WHERE LOWER(A.DESIGNATION) LIKE '%boulon%';

SELECT B.ID,
       B.NUMERO,
       SUM(C.QTE * A.PRIX) AS TOTAL_BON
FROM BON AS B
JOIN COMPO AS C   ON C.ID_BON = B.ID
JOIN ARTICLE AS A ON A.ID = C.ID_ART
GROUP BY B.ID, B.NUMERO;

SELECT B.ID,
       B.NUMERO,
       SUM(C.QTE) AS NB_ARTICLES
FROM BON AS B
JOIN COMPO AS C ON C.ID_BON = B.ID
GROUP BY B.ID, B.NUMERO;

SELECT B.NUMERO,
       SUM(C.QTE) AS NB_ARTICLES
FROM BON AS B
JOIN COMPO AS C ON C.ID_BON = B.ID
GROUP BY B.NUMERO
HAVING SUM(C.QTE) > 25;

SELECT SUM(C.QTE * A.PRIX) AS TOTAL_COMMANDES_AVRIL
FROM BON AS B
JOIN COMPO AS C   ON C.ID_BON = B.ID
JOIN ARTICLE AS A ON A.ID = C.ID_ART
WHERE B.DATE_CMDE >= '2019-04-01 00:00:00'
  AND B.DATE_CMDE <  '2019-05-01 00:00:00';

SELECT A1.ID           AS ID_ARTICLE_1,
       A1.DESIGNATION  AS DESIGNATION,
       F1.NOM          AS FOURNISSEUR_1,
       A2.ID           AS ID_ARTICLE_2,
       F2.NOM          AS FOURNISSEUR_2
FROM ARTICLE AS A1
JOIN ARTICLE AS A2
   ON A1.DESIGNATION = A2.DESIGNATION
  AND A1.ID_FOU <> A2.ID_FOURNISSEUR
  AND A1.ID < A2.ID
JOIN FOURNISSEUR AS F1 ON A1.ID_FOU = F1.ID
JOIN FOURNISSEUR AS F2 ON A2.ID_FOU = F2.ID;

SELECT YEAR(B.DATE_CMDE)  AS ANNEE,
       MONTH(B.DATE_CMDE) AS MOIS,
       SUM(C.QTE * A.PRIX) AS TOTAL_MOIS
FROM BON AS B
JOIN COMPO AS C   ON C.ID_BON = B.ID
JOIN ARTICLE AS A ON A.ID = C.ID_ART
GROUP BY YEAR(B.DATE_CMDE), MONTH(B.DATE_CMDE)
ORDER BY ANNEE, MOIS;

SELECT B.*
FROM BON AS B
WHERE NOT EXISTS (
    SELECT 1
    FROM COMPO AS C
    WHERE C.ID_BON = B.ID
);

SELECT F.NOM,
       AVG(T.TOTAL_BON) AS PRIX_MOYEN_BON
FROM (
    SELECT B.ID,
           B.ID_FOU,
           SUM(C.QTE * A.PRIX) AS TOTAL_BON
    FROM BON AS B
    JOIN COMPO AS C   ON C.ID_BON = B.ID
    JOIN ARTICLE AS A ON A.ID = C.ID_ART
    GROUP BY B.ID, B.ID_FOU
) AS T
JOIN FOURNISSEUR AS F ON T.ID_FOU = F.ID
GROUP BY F.ID, F.NOM;