USE compta;

UPDATE ARTICLE
SET DESIGNATION = LOWER(DESIGNATION)
WHERE ID = 2;

UPDATE ARTICLE
SET DESIGNATION = UPPER(DESIGNATION)
WHERE PRIX > 10;

UPDATE ARTICLE
SET PRIX = PRIX * 0.90
WHERE ID NOT IN (
    SELECT DISTINCT ID_ART
    FROM COMPO
);

UPDATE COMPO AS C
JOIN BON AS B        ON C.ID_BON = B.ID
JOIN FOURNISSEUR AS F ON B.ID_FOU = F.ID
SET C.QTE = C.QTE * 2
WHERE F.NOM = 'Française d''imports';

UPDATE ARTICLE
SET DESIGNATION = SUBSTRING(DESIGNATION, 1, POSITION('(' IN DESIGNATION) - 1)
WHERE DESIGNATION LIKE '%(%';
